import Mordell.ZsqrtdBasic

open Zsqrtd

namespace Mordell

/-!
# The quadratic order `ℤ[(1 + √d) / 2]`

For `d ≡ 1 [ZMOD 4]`, the full ring of integers of `ℚ(√d)` is generated by
`ω = (1 + √d) / 2`.  This file gives a concrete coordinate model `a + bω`
with `a b : ℤ`, complementing Mathlib's `ℤ√d`.
-/

/-- The quadratic order `ℤ[(1 + √d) / 2]`, represented as `a + bω`.

The generator satisfies `ω ^ 2 = ω + (d - 1) / 4`.  This is the right
integer-ring model when `d % 4 = 1`.
-/
abbrev Zomega (d : ℤ) := QuadraticAlgebra ℤ ((d - 1) / 4) 1

@[inherit_doc] notation "ℤω[" d "]" => Zomega d

namespace Zomega

/-- The generator `ω = (1 + √d) / 2`. -/
def omega (d : ℤ) : Zomega d :=
  (QuadraticAlgebra.omega : Zomega d)

@[simp]
lemma omega_re (d : ℤ) : (omega d).re = 0 :=
  rfl

@[simp]
lemma omega_im (d : ℤ) : (omega d).im = 1 :=
  rfl

lemma omega_sq (d : ℤ) :
    omega d ^ 2 = (((d - 1) / 4 : ℤ) : Zomega d) + omega d := by
  ext <;> simp [omega, pow_two]

/-- The element corresponding to `√d`, namely `2ω - 1`. -/
def sqrtd (d : ℤ) : Zomega d :=
  2 * omega d - 1

@[simp]
lemma sqrtd_re (d : ℤ) : (sqrtd d).re = -1 := by
  simp [sqrtd, omega, QuadraticAlgebra.re_one,
    QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

@[simp]
lemma sqrtd_im (d : ℤ) : (sqrtd d).im = 2 := by
  simp [sqrtd, omega, QuadraticAlgebra.im_one,
    QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

/-- The algebra norm in the `ω`-basis. -/
def norm {d : ℤ} (z : Zomega d) : ℤ :=
  QuadraticAlgebra.norm z

@[simp]
lemma norm_mul {d : ℤ} (z w : Zomega d) :
    norm (z * w) = norm z * norm w :=
  QuadraticAlgebra.norm.map_mul z w

@[simp]
lemma norm_pow {d : ℤ} (z : Zomega d) (n : ℕ) :
    norm (z ^ n) = norm z ^ n :=
  QuadraticAlgebra.norm.map_pow z n

lemma norm_mk (d a b : ℤ) :
    norm (⟨a, b⟩ : Zomega d) =
      a * a + a * b - ((d - 1) / 4) * b * b := by
  simp [norm, QuadraticAlgebra.norm_def, mul_comm]

private lemma four_dvd_sub_one_of_emod_eq_one {d : ℤ} (h_mod : d % 4 = 1) :
    (4 : ℤ) ∣ d - 1 := by
  have hmodeq : d ≡ 1 [ZMOD (4 : ℤ)] := by
    simpa [Int.ModEq] using h_mod
  have hdiv : (4 : ℤ) ∣ 1 - d := hmodeq.dvd
  simpa using (Int.dvd_neg.mpr hdiv)

private lemma int_cast_div_four_of_emod_eq_one (d : ℤ) (h_mod : d % 4 = 1) :
    (((d - 1) / 4 : ℤ) : ℚ) = ((d : ℚ) - 1) / 4 := by
  have hdiv : (4 : ℤ) ∣ d - 1 := four_dvd_sub_one_of_emod_eq_one h_mod
  calc
    (((d - 1) / 4 : ℤ) : ℚ) = ((d - 1 : ℤ) : ℚ) / (4 : ℚ) := by
      exact Int.cast_div hdiv (by norm_num)
    _ = ((d : ℚ) - 1) / 4 := by norm_num

private lemma four_mul_div_four_add_one_of_emod_eq_one (d : ℤ) (h_mod : d % 4 = 1) :
    4 * ((d - 1) / 4) + 1 = d := by
  have hdiv : (4 : ℤ) ∣ d - 1 := four_dvd_sub_one_of_emod_eq_one h_mod
  have hcancel : ((d - 1) / 4) * 4 = d - 1 :=
    Int.ediv_mul_cancel hdiv
  calc
    4 * ((d - 1) / 4) + 1 = ((d - 1) / 4) * 4 + 1 := by ring
    _ = (d - 1) + 1 := by rw [hcancel]
    _ = d := by ring

/-- Embed `ℤ[(1 + √d) / 2]` into the quadratic field model `QuadRat d`. -/
noncomputable def toQuadRat (d : ℤ) (h_mod : d % 4 = 1) : Zomega d →+* QuadRat d where
  toFun z := ⟨(z.re : ℚ) + (z.im : ℚ) / 2, (z.im : ℚ) / 2⟩
  map_zero' := by
    ext <;> simp
  map_one' := by
    ext <;> simp [QuadraticAlgebra.re_one, QuadraticAlgebra.im_one]
  map_add' z w := by
    ext <;> simp <;> ring
  map_mul' z w := by
    have hc := int_cast_div_four_of_emod_eq_one d h_mod
    ext <;> simp [QuadRat, hc] <;> ring

@[simp]
lemma toQuadRat_apply (d : ℤ) (h_mod : d % 4 = 1) (z : Zomega d) :
    toQuadRat d h_mod z =
      ⟨(z.re : ℚ) + (z.im : ℚ) / 2, (z.im : ℚ) / 2⟩ :=
  rfl

lemma toQuadRat_injective (d : ℤ) (h_mod : d % 4 = 1) :
    Function.Injective (toQuadRat d h_mod) := by
  intro z w h
  have himQ : (z.im : ℚ) / 2 = (w.im : ℚ) / 2 := by
    simpa using congrArg QuadraticAlgebra.im h
  have himQ' : (z.im : ℚ) = (w.im : ℚ) := by linarith
  have him : z.im = w.im := by exact_mod_cast himQ'
  have hreQ :
      (z.re : ℚ) + (z.im : ℚ) / 2 =
        (w.re : ℚ) + (w.im : ℚ) / 2 := by
    simpa using congrArg QuadraticAlgebra.re h
  have hreQ' : (z.re : ℚ) = (w.re : ℚ) := by
    rw [him] at hreQ
    linarith
  have hre : z.re = w.re := by exact_mod_cast hreQ'
  ext <;> assumption

/-- The old `ℤ√d` order maps into `ℤ[(1 + √d) / 2]` by `√d ↦ 2ω - 1`. -/
noncomputable def fromZsqrtd (d : ℤ) (h_mod : d % 4 = 1) : ℤ√d →+* Zomega d where
  toFun z := ⟨z.re - z.im, 2 * z.im⟩
  map_zero' := by
    ext <;> simp
  map_one' := by
    ext <;> simp [QuadraticAlgebra.re_one, QuadraticAlgebra.im_one]
  map_add' z w := by
    ext <;> simp <;> ring
  map_mul' z w := by
    have hc := four_mul_div_four_add_one_of_emod_eq_one d h_mod
    have hmul :
        d * z.im * w.im =
          (4 * ((d - 1) / 4) + 1) * z.im * w.im :=
      congrArg (fun t : ℤ => t * z.im * w.im) hc.symm
    ext <;> simp only [Zsqrtd.re_mul, Zsqrtd.im_mul, QuadraticAlgebra.mk_mul_mk, one_mul]
    · ring_nf
      rw [hmul]
      ring_nf
    · ring_nf

@[simp]
lemma fromZsqrtd_apply (d : ℤ) (h_mod : d % 4 = 1) (z : ℤ√d) :
    fromZsqrtd d h_mod z = ⟨z.re - z.im, 2 * z.im⟩ :=
  rfl

lemma fromZsqrtd_sqrtd (d : ℤ) (h_mod : d % 4 = 1) :
    fromZsqrtd d h_mod (Zsqrtd.sqrtd : ℤ√d) = sqrtd d := by
  ext <;> simp [sqrtd, omega, QuadraticAlgebra.re_one, QuadraticAlgebra.im_one,
    QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

lemma toQuadRat_fromZsqrtd (d : ℤ) (h_mod : d % 4 = 1) (z : ℤ√d) :
    toQuadRat d h_mod (fromZsqrtd d h_mod z) = zsqrtdToQuadRat d z := by
  ext <;> simp [zsqrtdToQuadRat_apply]

end Zomega

end Mordell
